#!/usr/bin/env bash
#

# ideally just run the proxy in a separate shell, then run the last command
kubectl proxy &
sleep 10
kubectl get ns $1 -o json | \
  jq '.spec.finalizers=[]' | \
  curl -X PUT http://localhost:8001/api/v1/namespaces/$1/finalize -H "Content-Type: application/json" --data @-  
