#!/usr/bin/env bash

set -euo pipefail

if [[ $# -lt 2 || $# -gt 3 ]]; then
  echo "kcpsecret: cp a k8s secret"
  echo "Usage: $0 <source-secret-name> <target-secret-name> [target-namespace]"
  exit 1
fi

SOURCE_SECRET="$1"
TARGET_SECRET="$2"
TARGET_NAMESPACE="${3:-default}"  # Default to "default" namespace if not provided

kubectl get secret "$SOURCE_SECRET" -o yaml \
  | yq 'del(.metadata.uid,
            .metadata.resourceVersion,
            .metadata.creationTimestamp,
            .metadata.selfLink,
            .metadata.annotations,
            .metadata.managedFields)
        | .metadata.name = "'"$TARGET_SECRET"'"
        | .metadata.namespace = "'"$TARGET_NAMESPACE"'"' \
  | kubectl apply -f -
