#!/usr/bin/env bash

nodes=($(kubectl get nodes | tail -n +2 | awk '{print $1}'))

for node in ${nodes[@]}; do
  echo "NODE: $node"

  kubectl get node $node -o custom-columns=INSTANCE:.metadata.labels."node\.kubernetes\.io/instance-type",IP:.status.addresses[0].address,NODEPOOL:.metadata.labels."karpenter\.sh/nodepool",CAPACITY:.metadata.labels."karpenter\.sh/capacity-type" --no-headers

  kubectl get pods --all-namespaces -o wide --field-selector spec.nodeName=$node
  echo
  echo
done
