#!/usr/bin/env bash
  

# Show PVs and their availability zones
kubectl get pv -o custom-columns=NAME:.metadata.name,ZONE:.spec.nodeAffinity.required.nodeSelectorTerms[0].matchExpressions[0].values[0],NAMESPACE:.spec.claimRef.namespace,CLAIM:.spec.claimRef.name,STORAGECLASS:.spec.storageClassName --sort-by='.spec.nodeAffinity.required.nodeSelectorTerms[0].matchExpressions[0].values[0]'
  
