#!/usr/bin/env bash

nodes=($(kubectl get nodes | tail -n +2 | awk '{print $1}'))

for node in ${nodes[@]}; do
  echo "NODE: $node"
  kubectl describe node $node | rg node.kubernetes.io/instance-type
  kubectl get pods --all-namespaces -o wide --field-selector spec.nodeName=$node
  echo
  echo
done

