#!/usr/bin/env bash
  
keys=$(kubectl describe secret $1 | tail -n +10 | awk '{print $1}')
for key in $keys; do
  cleaned=$(echo "${key::-1}")
  value=$(kubectl get "secret/${1}" "--template={{.data.${cleaned}}}" | base64 -D)
  echo "$cleaned: $value"
done
