after-login-command = []
start-at-login = true
accordion-padding = 20
enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false
default-root-container-layout = 'accordion'
default-root-container-orientation = 'vertical'

[gaps]
inner.horizontal = 15
inner.vertical =   15
outer.left =       15
outer.bottom =     15
outer.top =        15
outer.right =      15

[mode.main.binding]
cmd-h =         'focus left'
cmd-j =         'focus down'
cmd-k =         'focus up'
cmd-l =         'focus right'

cmd-shift-y = 'join-with left'
cmd-shift-o = 'join-with right'
cmd-shift-h = 'move left'
cmd-shift-l = 'move right'

cmd--f = 'fullscreen'
cmd-s = 'layout v_accordion'


# workspace 1 default accordion currently broken
cmd-0 = 'workspace 1'
cmd-1 = 'workspace 2'
cmd-2 = 'workspace 3'
cmd-3 = 'workspace 4'
cmd-4 = 'workspace 5'
cmd-5 = 'workspace 6'
# cmd-6 = 'workspace 6'
# cmd-7 = 'workspace 7'
# cmd-8 = 'workspace 8'
# cmd-9 = 'workspace 9'

cmd-shift-0 = 'move-node-to-workspace 1 --focus-follows-window'
cmd-shift-1 = 'move-node-to-workspace 2 --focus-follows-window'
cmd-shift-2 = 'move-node-to-workspace 3 --focus-follows-window'
cmd-shift-3 = 'move-node-to-workspace 4 --focus-follows-window'
cmd-shift-4 = 'move-node-to-workspace 5 --focus-follows-window'
cmd-shift-5 = 'move-node-to-workspace 6 --focus-follows-window'
# cmd-shift-6 = 'move-node-to-workspace 6 --focus-follows-window'
# cmd-shift-7 = 'move-node-to-workspace 7 --focus-follows-window'
# cmd-shift-8 = 'move-node-to-workspace 8 --focus-follows-window'
# cmd-shift-9 = 'move-node-to-workspace 9 --focus-follows-window'

cmd-shift-r = 'mode resize'

[mode.resize.binding]
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
enter = 'mode main'
esc = 'mode main'
