syn match cBraceL /{/
syn match cBraceR /}/
syn match cParenL /(/
syn match cParenR /)/
syn match cBracket /\[\]/
syn match cColon /:/
syn match cSemicolon /;/
syn match cEq /=/
syn match cPlus /+/
syn match cMinus /-/
syn match cDivide /\\/
syn match cStar /*/
syn match cAnd /&/
syn match cPipe /|/
syn match cPipeL /</
syn match cPipeR />/
syn match cPreprocessorLine '\#.*\n'
