source $NVIM_HOME/plugins/plugins-list.vim
source $NVIM_HOME/general-settings.vim
source $NVIM_HOME/key-mappings.vim
source $NVIM_HOME/commands.vim
source $NVIM_HOME/plugins/plugins-configs/nerd-tree.vim
source $NVIM_HOME/plugins/plugins-configs/vim-airline.vim
source $NVIM_HOME/plugins/plugins-configs/coc.vim
source $NVIM_HOME/plugins/plugins-configs/coc-metals.vim
source $NVIM_HOME/plugins/plugins-configs/commentary.vim
source $NVIM_HOME/plugins/plugins-configs/start-screen.vim
set termguicolors
