#!/bin/bash

# makes a script by touching file and adding shebang header
# $1 filename

if [ -z "$1" ]; then
  echo 'Missing $1: provide a script name'
  exit 1
fi

case "$(uname -s)" in
   Darwin)
      BASH="/usr/local/bin/bash"
     ;;
   Linux)
      BASH="/bin/bash"
     ;;
   *)
esac

cat << EOF > "$1"
#!${BASH}
  
  
EOF

chmod u+x "$1"

"$EDITOR" -c '3|star' "$1"
