#!/usr/bin/env bash

# run a connection test from a source context to a destination url
  
# $1 source context
# $2 destination url
kubectl --context=$1 run test-curl --image=curlimages/curl:latest --rm -i --tty --restart=Never -- curl -m 10 -I $2
  
