#!/usr/bin/env bash
  
if [[ -z $1 ]]; then
  echo "Please provide a file extension"
  exit 1
fi

while read -r file; do

  new_name=$(echo $file | sed 's/ //g')
  mv "${file}" $new_name

done < <(fd --extension $1)  
