vim.cmd('highlight clear')
if vim.fn.exists('syntax_on') then vim.cmd('syntax reset') end
vim.opt.termguicolors = true
vim.g.colors_name = 'meeahmi'

local c = require('core.colors')

vim.g.terminal_color_background = c.black
vim.g.terminal_color_foreground = c.offwhite

local function hl(group, opts)
  vim.api.nvim_set_hl(0, group, opts)
end

-- General Editor
hl('ColorColumn',   { bg = c.offblack })
hl('Cursor',        { fg = c.black,     bg = c.brightpink })
hl('CursorColumn',  { bg = c.offblack })
hl('CursorLine',    { bg = c.offblack })
hl('CursorLineNr',  { fg = c.midgray,   bold = true })
hl('ErrorMsg',      { fg = c.white,     bg = c.darkred,    bold = true })
hl('FoldColumn',    { fg = c.lightgray, bg = c.black })
hl('Folded',        { fg = c.brown,     bg = c.black,      bold = true })
hl('IncSearch',     { fg = c.white,     bg = c.lightgray })
hl('LineNr',        { fg = c.midgray })
hl('ModeMsg',       { fg = c.yellow })
hl('MoreMsg',       { fg = c.yellow })
hl('MsgArea',       { fg = c.yellow })
hl('NonText',       { fg = c.lightgray })
hl('Normal',        { fg = c.offwhite,  bg = c.black })
hl('Pmenu',         { fg = c.white,     bg = c.darkpurple })
hl('PmenuSel',      { fg = c.black,     bg = c.brightpink, bold = true })
hl('PmenuSbar',     { bg = c.darkgray })
hl('PmenuThumb',    { bg = c.lightgray })
hl('Question',      { fg = c.blue })
hl('Search',        { fg = c.white,     bg = c.lightgray })
hl('SignColumn',    { bg = c.black })
hl('SpecialKey',    { fg = c.lightgray })
hl('SpellCap',      { fg = c.blue,      undercurl = true })
hl('SpellBad',      { fg = c.darkred,   undercurl = true })
hl('StatusLine',    { fg = c.pink,      bg = c.darkpurple })
hl('StatusLineNC',  { fg = c.brightpink, bg = c.darkpurple })
hl('TabLineFill',   { fg = c.pink,      bg = c.black })
hl('TabLineSel',    { fg = c.black,     bg = c.darkgray })
hl('Title',         { fg = c.pink })
hl('Todo',          { fg = c.white,     bg = c.darkgray,   italic = true })
hl('VertSplit',     { fg = c.darkpurple })
hl('Visual',        { fg = c.brightpink, bg = c.darkgray })
hl('WarningMsg',    { fg = c.red })
hl('WildMenu',      { fg = c.black,     bg = c.cyan })
hl('NormalFloat',   { fg = c.offwhite,  bg = c.floatbg })
hl('FloatBorder',   { fg = c.red,       bg = c.floatbg })
hl('IblIndent',     { fg = c.indentline })

-- Diagnostics (sign-column letters/glyphs + virtual text)
hl('DiagnosticError',     { fg = c.red })
hl('DiagnosticWarn',      { fg = c.yellow })
hl('DiagnosticInfo',      { fg = c.blue })
hl('DiagnosticHint',      { fg = c.cyan })
hl('DiagnosticSignError', { fg = c.red })
hl('DiagnosticSignWarn',  { fg = c.yellow })
hl('DiagnosticSignInfo',  { fg = c.blue })
hl('DiagnosticSignHint',  { fg = c.cyan })

-- Syntax
hl('Boolean',       { fg = c.green })
hl('Delimiter',     { fg = c.tan })
hl('Character',     { fg = c.red })
hl('Comment',       { fg = c.midgray,   italic = true })
hl('Conceal',       { fg = c.brown,     bg = c.black })
hl('Constant',      { fg = c.white })
hl('Conditional',   { fg = c.green })
hl('Constructor',   { fg = c.green })
hl('Error',         { bg = c.darkred })
hl('Exception',     { fg = c.green })
hl('Function',      { fg = c.offwhite })
hl('Identifier',    { fg = c.offwhite })
hl('Include',       { fg = c.purple })
hl('Keyword',       { fg = c.green })
hl('Statement',     { fg = c.blue })
hl('Operator',      { fg = c.cyan })
hl('PreProc',       { fg = c.purple })
hl('Define',        { fg = c.purple })
hl('Macro',         { fg = c.purple })
hl('Number',        { fg = c.yellow })
hl('String',        { fg = c.orange })
hl('Structure',     { fg = c.cyan })
hl('Special',       { fg = c.brightpink })
hl('Type',          { fg = c.blue })
hl('Underlined',    { fg = c.blue })

-- Plugins
hl('MatchParen',              { fg = c.cyan,    bg = c.brightpink, bold = true })
hl('GitGutterAdd',            { fg = c.green })
hl('GitGutterChange',         { fg = c.yellow })
hl('GitGutterChangeDelete',   { fg = c.orange })
hl('GitGutterDelete',         { fg = c.red })
hl('Directory',               { fg = c.pink })
-- hl('NerdTreeCWD',             { fg = c.white })
-- hl('NerdTreeFile',            { fg = c.purple })
-- hl('NERDTree',                { bg = c.black })

-- TreeSitter
-- hl('TSAnnotation',      { fg = c.purple,   bold = true })
-- hl('TSBoolean',         { fg = c.green })
-- hl('TSCharacter',       { fg = c.orange })
-- hl('TSComment',         { fg = c.midgray })
-- hl('TSConditional',     { fg = c.green })
-- hl('TSConstBuiltin',    { fg = c.green })
-- hl('TSConstMacro',      { fg = c.purple })
-- hl('TSConstant',        { fg = c.offwhite })
-- hl('TSConstructor',     { fg = c.blue })
-- hl('TSException',       { fg = c.green })
-- hl('TSError',           {})
-- hl('TSFloat',           { fg = c.yellow })
-- hl('TSKeywordFunction', { fg = c.green })
-- hl('TSKeywordOperator', { fg = c.green })
-- hl('TSInclude',         { fg = c.purple })
-- hl('TSKeyword',         { fg = c.green })
-- hl('TSMethod',          { fg = c.white })
-- hl('TSFuncBuiltin',     { fg = c.beige })
-- hl('TSFuncMacro',       { fg = c.purple })
-- hl('TSOperator',        { fg = c.cyan })
-- hl('TSParameter',       { fg = c.offwhite })
-- hl('TSProperty',        { fg = c.white })
-- hl('TSPunctBracket',    { fg = c.tan })
-- hl('TSPunctDelimiter',  { fg = c.tan })
-- hl('TSPunctSpecial',    { fg = c.cyan })
-- hl('TSRepeat',          { fg = c.green })
-- hl('TSString',          { fg = c.orange })
-- hl('TSStringEscape',    { fg = c.brown })
-- hl('TSTag',             { fg = c.blue })
-- hl('TSTagAttribute',    { fg = c.paleblue })
-- hl('TSTagDelimiter',    { fg = c.tan })
-- hl('TSTernary',         { fg = c.cyan })
-- hl('TSTextReference',   { fg = c.yellow })
-- hl('TSTitle',           { fg = c.pink })
-- hl('TSType',            { fg = c.blue })
-- hl('TSTypeBuiltin',     { fg = c.blue })
-- hl('TSURI',             { fg = c.brown })
-- hl('TSVariable',        { fg = c.offwhite })
-- hl('TSVariableBuiltin', { fg = c.beige })

-- Lang Overrides
-- hl('pythonDecoratorName',          { fg = c.red })
-- hl('pythonFunction',               { fg = c.white })
hl('markdownBold',                 { fg = c.yellow,  bold = true })
hl('markdownCode',                 { fg = c.cyan })
hl('markdownCodeBlock',            { fg = c.cyan })
hl('markdownCodeDelimiter',        { fg = c.cyan })
hl('markdownHeadingDelimiter',     { fg = c.green })
hl('markdownHeadingRule',          { fg = c.midgray })
hl('markdownId',                   { fg = c.purple })
hl('markdownItalic',               { fg = c.blue,    italic = true })
hl('markdownListMarker',           { fg = c.orange })
hl('markdownOrderedListMarker',    { fg = c.orange })
hl('markdownRule',                 { fg = c.midgray })
hl('markdownUrl',                  { fg = c.purple })
hl('markdownUrlTitleDelimiter',    { fg = c.green })
hl('typescriptUnaryOp',            { fg = c.cyan })
hl('jsonCommentError',             { fg = c.darkgray })
hl('jsonBoolean',                  { fg = c.green })

-- Treesitter @ captures
hl('@type.qualifier',    { fg = c.green })
hl('@type.builtin',      { fg = c.green })
hl('@attribute.builtin', { fg = c.purple })
hl('@variable.builtin',  { fg = c.offwhite })
